config/routes.rb
Rails.application.routes.draw do
  resources :media

  get 'my_page', to: 'my_page#index'

  devise_for :users, controllers: { sessions: 'sessions' }

  get 'home', to: 'home#index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :user
  has_many :medium_tags, dependent: :destroy
  has_many :tags, through: :medium_tags

  mount_uploader :file, MediaUploader

  attr_accessor :tag_names

  validates :name, presence: true

  before_save :normalize

  def save_tags(tag_names)
    MediumTag.where(medium_id: id).destroy_all if tags.present?

    tag_names.each do |tag|
      inspected_tag = Tag.where(name: tag).first_or_create
      tags << inspected_tag
    end
  end

  def move_file(from, thumbnail_from)
    to = file.path
    thumbnail_to = file.thumb.path
    return if from == to

    move_file_sub(from, to)
    move_file_sub(thumbnail_from, thumbnail_to)
  end

  private

  def move_file_sub(from, to)
    FileUtils.mkdir_p(File.dirname(to))
    FileUtils.mv(from, to)
    FileUtils.rm_r(File.dirname(from), secure: true)
    begin
      FileUtils.rmdir(File.dirname(from, 2))
    rescue Errno::ENOTEMPTY
      # 削除できなければ無視して続行
    end
  end

  def normalize
    author.tr!('\\', '＼')
    author.tr!('/', '／')
    author.tr!(':', '：')
    author.tr!('*', '＊')
    author.tr!('?', '？')
    author.tr!('<', '＜')
    author.tr!('>', '＞')
    author.tr!('|', '｜')
  end
end

app/models/medium_tag.rb
class MediumTag < ApplicationRecord
  belongs_to :medium
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :medium_tags, dependent: :destroy
  has_many :media, through: :medium_tags

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :media, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :authenticate_user!
  before_action :set_medium, only: %i[show edit update destroy]

  # GET /media or /media.json
  def index
    @tag_name = params[:tag]
    tag = Tag.find_by(name: @tag_name)
    media = tag&.media || Medium.all
    @pagy, @media = pagy(media.where(user: current_user))
  end

  # GET /media/1 or /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media or /media.json
  def create
    @medium = Medium.new(medium_params)
    @medium.user_id = current_user.id
    tag_names = params[:medium][:tag_names].split
    @medium.save_tags(tag_names)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to medium_url(@medium), notice: t('.created') }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1 or /media/1.json
  def update
    tag_names = params[:medium][:tag_names].split
    @medium.save_tags(tag_names)

    respond_to do |format|
      from = @medium.file.path
      thumbnail_from = @medium.file.thumb.path
      if @medium.update(medium_params)
        @medium = Medium.find(@medium.id) # 読み直さないと新しいパスにならない
        @medium.move_file(from, thumbnail_from)
        format.html { redirect_to medium_url(@medium), notice: t('.updated') }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1 or /media/1.json
  def destroy
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url, notice: t('.deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_medium
    @medium = Medium.find(params[:id])
    @medium.tag_names = []
    @medium.tags.each do |tag|
      @medium.tag_names << tag.name
    end
  end

  # Only allow a list of trusted parameters through.
  def medium_params
    params.require(:medium).permit(:name, :author, :file, :file_cache)
  end
end

app/controllers/my_page_controller.rb
class MyPageController < ApplicationController
  before_action :authenticate_user!

  def index
    @tag_name = params[:tag]
    tag = Tag.find_by(name: @tag_name)
    media = tag&.media || Medium.all
    @pagy, @media = pagy(media.where(user: current_user))
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def respond_to_on_destroy
    respond_to do |format|
      # format.all { head :no_content }
      # format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: :see_other }
      format.any(*navigational_formats) { redirect_to root_path, status: :see_other }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/my_page_helper.rb
module MyPageHelper
end

app/views/home/index.html.slim
.my-2
  = link_to('一覧', media_path, class: 'btn btn-normal')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Javelin collector
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    / = stylesheet_link_tag "tailwind", "inter-font"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    / = stylesheet_link_tag "application"
    = javascript_importmap_tags

  body
    nav.bg-green-100.py-4
      .flex.justify-between
        #title.ml-4
          | Javelin collector
        - if user_signed_in?
          #menu.mr-4
            = link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-normal'

    main.container.mx-auto
      .text-center
        .alert
          = alert
        .notice
          = notice

      = yield

app/views/media/_form.html.slim
= form_with(model: @medium) do |form|
  - if @medium.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@medium.errors.count, "error")} prohibited this medium from being saved:"
      ul
        - @medium.errors.each do |error|
          li = error.full_message

  dl
    dt.label = form.label :name
    dd = form.text_field :name

    dt.label = form.label :author
    dd = form.text_field :author

    dt.label = form.label :tag_names
    dd = form.text_field :tag_names, placeholder: '空白で区切ってください'
  
    dt.label = form.label :file
    dd
      - if @medium.id.present?
        = image_tag @medium.file.thumb.url
        .hidden = form.file_field :file
      - else
        = form.file_field :file
      = form.hidden_field :file_cache

  .inline-block.mt-2
    = form.submit(class: 'btn btn-normal')
    = link_to "戻る", media_path, class: 'btn btn-cancel ml-4'

app/views/media/_medium.html.slim
div id="#{dom_id medium}"
  .thumbnail_outer
    - if medium.file.content_type.include?('video/')
      = video_tag medium.file.url, controls: true, autobuffer: true, class: 'thumbnail'
    - else
      = image_tag medium.file.thumb.url, class: 'thumbnail'
  .name
    = "#{medium.name} / #{medium.author}"

app/views/media/edit.html.slim
h1 編集

== render "form", medium: @medium

br

div
  = link_to '戻る', media_path, class: 'btn btn-cancel'

app/views/media/index.html.slim
h1.inline-block.py-4 一覧
.inline-block.ml-4
  = link_to('新規登録', new_medium_path, class: 'btn btn-normal')
.inline-block.ml-4
  = form_with(url: media_path, method: :get) do |f|
    = f.text_field :tag, placeholder: 'タグ検索', value: @tag_name
    = f.submit('検索', class: 'btn btn-normal ml-2')

.pagy_nav
  == pagy_nav(@pagy)

#media
  - @media.each do |medium|
    = link_to medium do
      == render medium

.pagy_nav
  == pagy_nav(@pagy)

app/views/media/new.html.slim
h1 新規登録

== render "form", medium: @medium

app/views/media/show.html.slim
.medium
  - if @medium.file.content_type.include?('video/')
    = video_tag @medium.file.url, controls: true, autobuffer: true
  - else
    = image_tag @medium.file.url

.title
  = "#{@medium.name} / #{@medium.author}"

.tags
  - @medium.tags.each do |tag|
    .tag = tag.name

.flex.justify-between
  .buttons.py-4
    = link_to "更新", edit_medium_path(@medium), class: 'btn btn-normal'
    = link_to "戻る", media_path, class: 'btn btn-cancel ml-4'

  .buttons2.py-2
    = button_to "削除", @medium, method: :delete, class: 'btn btn-danger', form: { data: { turbo_confirm: '削除してよろしいですか？' } }

app/views/my_page/index.html.slim
.my-2
  = link_to('全表示', media_path, class: 'btn btn-normal')

h1.inline-block.py-4 一覧
.inline-block.ml-4
  = link_to('新規登録', new_medium_path, class: 'btn btn-normal')
.inline-block.ml-4
  = form_with(url: my_page_path, method: :get) do |f|
    = f.text_field :tag, placeholder: 'タグ検索', value: @tag_name
    = f.submit('検索', class: 'btn btn-normal ml-2')

.pagy_nav
  == pagy_nav(@pagy)

#media
  - @media.each do |medium|
    = link_to medium do
      == render medium

.pagy_nav
  == pagy_nav(@pagy)

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "サインアップ", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "パスワードを忘れた場合", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    br